#Trac_Ik
kanan:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_search_resolution: 0.3
  kinematics_solver_timeout: 0.05
kiri:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_search_resolution: 0.03
  kinematics_solver_timeout: 0.05
badan:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_search_resolution: 0.03
  kinematics_solver_timeout: 0.05
kaki:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005

# #srv 
# kanan:
#   kinematics_solver: srv_kinematics_plugin/SrvKinematicsPlugin
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.005
# kiri:
#   kinematics_solver: srv_kinematics_plugin/SrvKinematicsPlugin
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.005
# badan:
#   kinematics_solver: srv_kinematics_plugin/SrvKinematicsPlugin
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.005
# kaki:
#   kinematics_solver: srv_kinematics_plugin/SrvKinematicsPlugin
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.005

# #lma
# kanan:
#   kinematics_solver: lma_kinematics_plugin/LMAKinematicsPlugin
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.005
# kiri:
#   kinematics_solver: lma_kinematics_plugin/LMAKinematicsPlugin
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.005
# badan:
#   kinematics_solver: lma_kinematics_plugin/LMAKinematicsPlugin
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.005
# kaki:
#   kinematics_solver: lma_kinematics_plugin/LMAKinematicsPlugin
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.005

# #kdl
# kanan:
#   kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.005
# kiri:
#   kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.005
# badan:
#   kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.005
# kaki:
#   kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.005

# #cached_ik_srv
# kanan:
#   kinematics_solver: cached_ik_kinematics_plugin/CachedSrvKinematicsPlugin
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.005
# kiri:
#   kinematics_solver: cached_ik_kinematics_plugin/CachedSrvKinematicsPlugin
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.005
# badan:
#   kinematics_solver: cached_ik_kinematics_plugin/CachedSrvKinematicsPlugin
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.005
# kaki:
#   kinematics_solver: cached_ik_kinematics_plugin/CachedSrvKinematicsPlugin
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.005

# #cached_ik_kdl
# kanan:
#   kinematics_solver: cached_ik_kinematics_plugin/CachedKDLKinematicsPlugin
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.005
# kiri:
#   kinematics_solver: cached_ik_kinematics_plugin/CachedKDLKinematicsPlugin
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.005
# badan:
#   kinematics_solver: cached_ik_kinematics_plugin/CachedKDLKinematicsPlugin
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.005
# kaki:
#   kinematics_solver: cached_ik_kinematics_plugin/CachedKDLKinematicsPlugin
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.005